services:
    universal-mcp-server:
        image: your-username/telegram-mcp-server:latest
        ports:
            - '8080:8080'
        environment:
            - NODE_ENV=production
            - PORT=8080
            - DOCKER_ENV=true
        env_file:
            - .env
        restart: unless-stopped
        labels:
            - "coolify.managed=true"
            - "coolify.name=telegram-mcp-server"
        healthcheck:
            test:
                [
                    'CMD',
                    'curl',
                    '-f',
                    'http://localhost:8080',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s 